AWSTemplateFormatVersion: '2010-09-09'

Description: Multi Environment CloudFront Distribution For Portfolio Website

Parameters:

  ProjectName:
    Type: String
    Default: aws-portfolio

Resources:

  # =========================================================
  # STAGING CLOUDFRONT DISTRIBUTION
  # =========================================================

  StagingDistribution:
    Type: AWS::CloudFront::Distribution

    Properties:

      DistributionConfig:

        Enabled: true

        Comment: Staging CloudFront Distribution

        DefaultRootObject: index.html

        Origins:

          - Id: StagingS3Origin

            DomainName: !Sub "${ProjectName}-staging-${AWS::AccountId}.s3-website-${AWS::Region}.amazonaws.com"

            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only

        DefaultCacheBehavior:

          TargetOriginId: StagingS3Origin

          ViewerProtocolPolicy: redirect-to-https

          AllowedMethods:
            - GET
            - HEAD

          CachedMethods:
            - GET
            - HEAD

          ForwardedValues:
            QueryString: false

        PriceClass: PriceClass_100

  # =========================================================
  # PRODUCTION CLOUDFRONT DISTRIBUTION
  # =========================================================

  ProductionDistribution:
    Type: AWS::CloudFront::Distribution

    Properties:

      DistributionConfig:

        Enabled: true

        Comment: Production CloudFront Distribution

        DefaultRootObject: index.html

        Origins:

          - Id: ProductionS3Origin

            DomainName: !Sub "${ProjectName}-prod-${AWS::AccountId}.s3-website-${AWS::Region}.amazonaws.com"

            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only

        DefaultCacheBehavior:

          TargetOriginId: ProductionS3Origin

          ViewerProtocolPolicy: redirect-to-https

          AllowedMethods:
            - GET
            - HEAD

          CachedMethods:
            - GET
            - HEAD

          ForwardedValues:
            QueryString: false

        PriceClass: PriceClass_100

Outputs:

  StagingDistributionId:
    Description: Staging CloudFront Distribution ID
    Value: !Ref StagingDistribution

  StagingDistributionDomain:
    Description: Staging CloudFront URL
    Value: !GetAtt StagingDistribution.DomainName

  ProductionDistributionId:
    Description: Production CloudFront Distribution ID
    Value: !Ref ProductionDistribution

  ProductionDistributionDomain:
    Description: Production CloudFront URL
    Value: !GetAtt ProductionDistribution.DomainName