name: Deploy Portfolio S3 Infrastructure And Website

on:

  push:
    branches:
      - main

jobs:

  # =====================================================
  # JOB 1 — STAGING
  # =====================================================

  deploy-staging:

    name: Deploy To Staging

    runs-on: ubuntu-latest

    steps:

      # ==========================================
      # CHECKOUT REPOSITORY
      # ==========================================

      - name: Checkout Repository
        uses: actions/checkout@v4

      # ==========================================
      # CONFIGURE AWS CREDENTIALS
      # ==========================================

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # ==========================================
      # DEPLOY S3 INFRASTRUCTURE ONLY
      # ==========================================

      - name: Deploy S3 Infrastructure
        run: |

          aws cloudformation deploy \
          --template-file infrastructure/cloudformation/s3.yaml \
          --stack-name aws-portfolio-s3

      # ==========================================
      # GET AWS ACCOUNT ID
      # ==========================================

      - name: Get AWS Account ID
        run: |

          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

          echo "ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV

      # ==========================================
      # DEPLOY WEBSITE TO STAGING S3
      # ==========================================

      - name: Deploy Website To STAGING S3
        run: |

          aws s3 sync website/ s3://aws-portfolio-staging-${ACCOUNT_ID} --delete

  # =====================================================
  # JOB 2 — PRODUCTION
  # =====================================================

  deploy-production:

    name: Deploy To Production

    needs: deploy-staging

    runs-on: ubuntu-latest

    environment:
      name: production

    steps:

      # ==========================================
      # CHECKOUT REPOSITORY
      # ==========================================

      - name: Checkout Repository
        uses: actions/checkout@v4

      # ==========================================
      # CONFIGURE AWS CREDENTIALS
      # ==========================================

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # ==========================================
      # GET AWS ACCOUNT ID
      # ==========================================

      - name: Get AWS Account ID
        run: |

          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

          echo "ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV

      # ==========================================
      # DEPLOY WEBSITE TO PROD S3
      # ==========================================

      - name: Deploy Website To PROD S3
        run: |

          aws s3 sync website/ s3://aws-portfolio-prod-${ACCOUNT_ID} --delete