name: Deploy Portfolio Infrastructure And Website

on:

  push:
    branches:
      - main

jobs:

  # =====================================================
  # JOB 1 — STAGING
  # =====================================================

  deploy-staging:

    name: Deploy To Staging

    runs-on: ubuntu-latest

    steps:

      # ==========================================
      # CHECKOUT REPOSITORY
      # ==========================================

      - name: Checkout Repository
        uses: actions/checkout@v4

      # ==========================================
      # CONFIGURE AWS CREDENTIALS
      # ==========================================

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # ==========================================
      # DEPLOY CLOUDFORMATION INFRASTRUCTURE
      # ==========================================

      - name: Deploy CloudFront Infrastructure
        run: |

          aws cloudformation deploy \
          --template-file infrastructure/cloudformation/cloudfront.yaml \
          --stack-name aws-portfolio-cloudfront

      # ==========================================
      # GET AWS ACCOUNT ID
      # ==========================================

      - name: Get AWS Account ID
        run: |

          echo "ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

      # ==========================================
      # DEPLOY WEBSITE TO STAGING S3
      # ==========================================

      - name: Deploy Website To STAGING S3
        run: |

          aws s3 sync website/ s3://aws-portfolio-staging-${ACCOUNT_ID} --delete

      # ==========================================
      # GET STAGING DISTRIBUTION ID
      # ==========================================

      - name: Get Staging Distribution ID
        run: |

          echo "STAGING_DISTRIBUTION_ID=$(aws cloudformation describe-stacks \
          --stack-name aws-portfolio-cloudfront \
          --query \"Stacks[0].Outputs[?OutputKey=='StagingDistributionid'].OutputValue\" \
          --output text)" >> $GITHUB_ENV

      # ==========================================
      # INVALIDATE STAGING CLOUDFRONT CACHE
      # ==========================================

      - name: Invalidate STAGING CloudFront Cache
        run: |

          aws cloudfront create-invalidation \
          --distribution-id ${STAGING_DISTRIBUTION_ID} \
          --paths "/*"

  # =====================================================
  # JOB 2 — PRODUCTION
  # =====================================================

  deploy-production:

    name: Deploy To Production

    needs: deploy-staging

    runs-on: ubuntu-latest

    environment:
      name: production

    steps:

      # ==========================================
      # CHECKOUT REPOSITORY
      # ==========================================

      - name: Checkout Repository
        uses: actions/checkout@v4

      # ==========================================
      # CONFIGURE AWS CREDENTIALS
      # ==========================================

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # ==========================================
      # GET AWS ACCOUNT ID
      # ==========================================

      - name: Get AWS Account ID
        run: |

          echo "ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

      # ==========================================
      # DEPLOY WEBSITE TO PROD S3
      # ==========================================

      - name: Deploy Website To PROD S3
        run: |

          aws s3 sync website/ s3://aws-portfolio-prod-${ACCOUNT_ID} --delete

      # ==========================================
      # GET PRODUCTION DISTRIBUTION ID
      # ==========================================

      - name: Get Production Distribution ID
        run: |

          echo "PRODUCTION_DISTRIBUTION_ID=$(aws cloudformation describe-stacks \
          --stack-name aws-portfolio-cloudfront \
          --query \"Stacks[0].Outputs[?OutputKey=='ProductionDistributionid'].OutputValue\" \
          --output text)" >> $GITHUB_ENV

      # ==========================================
      # INVALIDATE PRODUCTION CLOUDFRONT CACHE
      # ==========================================

      - name: Invalidate PROD CloudFront Cache
        run: |

          aws cloudfront create-invalidation \
          --distribution-id ${PRODUCTION_DISTRIBUTION_ID} \
          --paths "/*"